Use permissive instead of strict mTLS
This commit switches back to PERMISSIVE from STRICT enforcement of mTLS.
The reason is that initContainers start before envoy, but are not
allowed to communicate without mTLS. The result was:

```bash
$ kubectl logs -n api  api-6d58cd4646-vbs4x -c
migrations
error: read tcp 172.17.0.9:37508->10.101.250.224:5432: read: connection
reset by peer
```

Changing this setting back to permissive allows the initial connection
to the database to happen with mTLS, which is pretty unsatisfactory, but
it looks like this might be resolvable by using Istio as a CNI plugin:
https://istio.io/latest/docs/setup/additional-setup/cni/#install-cni

That will be explored separately.